### PR TITLE
Merge v1.13.0 into develop

### PR DESCRIPTION
**Pull request by cea2aj**
Resolve merge conflicts to merge v1.13.0 into develop

### CODE REVIEW

**Review by nmanu1 — COMMENTED** [review]
Looks like a Snyk check is failing. Did the package-lock changes revert some of the package upgrades for fixing vulnerabilities?

**Comment by oshi97** [comment]
I think it's possible the package-lock changes are upsetting snyk?

**Comment by cea2aj** [comment]
> Looks like a Snyk check is failing. Did the package-lock changes revert some of the package upgrades for fixing vulnerabilities?

I checked the package.json, and the synk fixes from #1675 are still present. I looked through the reported issues in synk, and they are coming from jest@24.9.0, enzyme@3.11.0, @percy/cli@1.0.0-beta.65, and gulp@4.0.2. These versions are present in master and in develop (with the exception of the percy/cli which uses a newer version of the percy/cli in develop). As a result, I believe the synk issues are new issues reported on Snyk for existing dependencies, and not a result of this PR which would be the role of the slapshot responder to address.

**Comment by oshi97** [comment]
should the package-lock be getting updated here? I would have thought develop would have priority

**Comment by cea2aj** [comment]
> should the package-lock be getting updated here? I would have thought develop would have priority

Master uses package-lock version 1 and develop uses version 2, so there were significant conflicts. I deleted the package-lock and made a new one on node 14.17.6 and npm 8.6.0.

**Comment by oshi97** [comment]
> > should the package-lock be getting updated here? I would have thought develop would have priority
> 
> Master uses package-lock version 1 and develop uses version 2, so there were significant conflicts. I deleted the package-lock and made a new one on node 14.17.6 and npm 8.6.0.

Deleting and regenerating the package-lock will update a number of dependencies, but I'm fine with that

**Comment by oshi97** [comment]
> > should the package-lock be getting updated here? I would have thought develop would have priority
> 
> Master uses package-lock version 1 and develop uses version 2, so there were significant conflicts. I deleted the package-lock and made a new one on node 14.17.6 and npm 8.6.0.

Alternatively, since no dependencies in the package.json were changed at all, I don't think we would need to address merge conflicts and could just use the package-lock on develop verbatim. But, again, I think it's fine if we want to regenerate it. At this point the SDK has good test coverage, if a little messy, but we shouldn't run into issues for say updating a babel plugin to the latest hotfix.

**Review by oshi97 — APPROVED** [review]

**Pull request merged**
