### PR TITLE
Add dependabot config file for security monitoring

### PR DESCRIPTION
**Pull request by MattCBowman**

### CODE REVIEW

**Review by tmeyer2115 — APPROVED** [review]
LGTM! I'm not sure what we'll do with this PR. We can't merge it, since we decided to only have Dependabot run in 'develop' for now. We could keep this PR open (and assign some indicative label to it). Or, we could manually create a 'develop' branch on the remote and change this PR to merge into the 'develop' branch.

**Comment by MattCBowman** [comment]
> LGTM! I'm not sure what we'll do with this PR. We can't merge it, since we decided to only have Dependabot run in 'develop' for now. We could keep this PR open (and assign some indicative label to it). Or, we could manually create a 'develop' branch on the remote and change this PR to merge into the 'develop' branch.

It's only attached to branches that we point it at, so it's only going to be looking at develop for now. We can merge without dependabot grabbing master

**Comment by tmeyer2115** [comment]
> > LGTM! I'm not sure what we'll do with this PR. We can't merge it, since we decided to only have Dependabot run in 'develop' for now. We could keep this PR open (and assign some indicative label to it). Or, we could manually create a 'develop' branch on the remote and change this PR to merge into the 'develop' branch.
> 
> It's only attached to branches that we point it at, so it's only going to be looking at develop for now. We can merge without dependabot grabbing master

Our current paradigm is to merge only release branches into master. Could we make this part of the next release?

**Comment by tmeyer2115** [comment]
Closing this PR for now. We need to make a new develop branch via git flow. Once that's done, I will remake this PR for the new develop

**Pull request closed without merging**
