### PR TITLE
VerticalResults: use old no results when noResults config option is n…

### PR DESCRIPTION
**Pull request by oshi97**
…ot set

TEST=manual
Tested that when there is no noResults config option set, will
use the old no results template. Otherwise, will use the new one.

### CODE REVIEW

**Review by alexisgrow — COMMENTED** [review]
Instead of branching in the hbs, what do you think about having the logic in JS?

**Comment by oshi97** [comment]
> Instead of branching in the hbs, what do you think about having the logic in JS?

sure that makes sense

**Review by alexisgrow — APPROVED** [review]
LGTM! 🔥

**Review by alexisgrow — COMMENTED** [review]
Also! Talked to Rose and this should be merged into v0.13.1 🎉 
(because the fancy no results is still behind a feature flag, so can't be default behavior yet)

**Pull request merged**
