### PR TITLE
Cards: Allow custom card type for custom card components

### PR DESCRIPTION
**Pull request by alexisgrow**
If a user enters a cardType that is built in, no changes. If
they enter a cardYype that is not built in, the library interprets
it as a component name.

TEST=manual

Update the config to use built in vs custom cardTypes. Observe
chaanges in browser.

### CODE REVIEW

**Review by oshi97 — COMMENTED** [review]
lgtm!

**Review by oshi97 — APPROVED** [review]
omg I'm dying

**Comment by oshi97** [comment]
I'm so sorry

**Comment by MattCBowman** [comment]
🤣

**Pull request merged**
