### PR TITLE
Version v1.5.0

### PR DESCRIPTION
**Pull request by creotutar**
# Version 1.5.0

Version 1.5.0 comes with the addition of query rules. Users can start with the context and referrerPageUrl parameters in their experience. We also have various additions to our existing components: top-level appliedFilters config, a direct answer override config option.

## Changes

* Query Rules: Referrer Page URL. A new query parameter `referrerPageUrl` in the answers URL will allow users to use referrer page information when constructing query rules.

* Query Rules: Context. Users can set context for the experience. This context can be used to construct query rules. This manifests as the query parameter `context`. Users can use the new `ANSWERS.setContext` function.

* FilterOptions: add css variables for checkmark colors. Users can set the checkmark color with the variable `--yxt-filter-options-checkmark-color` and the checkbox outline color on focus with `--yxt-filter-options-checkbox-focus-color`.

* UniversalResults: add top-level appliedFilters config. Users can change appliedFilters across all verticals.

* DirectAnswer: add cardOverrides. Users can now choose a custom direct answer card depending on the answer's fieldName, entityType, and fieldType.

* Expose FilterNodeFactory: Users can now more easily interact with our filter node system.

* Various circleci changes for engineering development improvements: Remove max-age cache for canary/latest, use node version 14.5 for circleci, remove manual hold for develop canary branches.

## Styling Updates

* FilterOptions checkmarks are now yxt-color-brand-primary instead of yxt-color-hover.

### CODE REVIEW

**Comment by oshi97** [comment]
>DirectAnswer: add cardOverrides. Users can override the direct answer depending on the fieldName, entityType, and fieldType

"Users can now choose a custom direct answer card depending on the answer's fieldName, entityType, and fieldType."

> Expose FilterNodeFactory: Users can now interact with our filter node system directly.

maybe "We made it easier to interact directly with our filter system."? They could always interact with the system directly it was just a massive pain (honestly doubt anybody but me will be picky about this lol)

**Comment by tmeyer2115** [comment]
> * in the answers URL will allow users to use referrer page information in a backend answers search configuration. This is nothing

Remove "this is nothing". We can be a bit more accurate by saying "allow users to use referrer page information when constructing query rules". Similarly, for context we can say "for use in constructing query rules".

**Comment by tmeyer2115** [comment]
> * FilterOptions: add css variables for checkmark colors. Users can set the checkmark color with variables `--yxt-filter-options-checkmark-color` and `--yxt-filter-options-checkbox-focus-color`

The focus-color variable is, I believe, not for the checkmark color. It controls the color of the outline of the checkbox when it is in the focus state.

**Review by tmeyer2115 — APPROVED** [review]

**Review by tmeyer2115 — APPROVED** [review]

**Review by oshi97 — APPROVED** [review]
lgtm!

**Pull request merged**
