### PR TITLE
sass: Set explicit width on result images

### PR DESCRIPTION
**Pull request by data-enabler**
Most browsers (except Firefox) have bugs that prevent img elements
inside flex containers from shrinking. Set an explicit width on
yxt-Result-image as a workaround.

Fixes #312

### CODE REVIEW

**Review by benmcginnis — DISMISSED** [review]

**Comment by benmcginnis** [comment]
What is this cool data enabler thing @Delerme ?

**Comment by Delerme** [comment]
It's Adrian, another engineer on the team

**Comment by benmcginnis** [comment]
Oh lol, based on the handle, I thought it was a magical bot identifying
browser bugs

**Comment by Delerme** [comment]
Yea same, luckily Adrian is just as magical if not more

**Comment by data-enabler** [comment]
@benmcginnis Had to rebase. No changes otherwise.

**Review by benmcginnis — APPROVED** [review]

**Pull request merged**
